### ISSUE TITLE
The app icon change in update

### ISSUE THREAD

**Issue by Thewisem** [ferraridamiano/ConverterNOW#104]
The app icon changed to default android icon that system apps have in the new update. Could you fix that

**Comment by ferraridamiano** [comment]
Mmmm, it's strange, could you send me a screenshot?

**Comment by Thewisem** [comment]
![Screenshot_20210923-185710](https://user-images.githubusercontent.com/74511929/134542377-02030d54-324f-4e04-bd74-f1f4b879de93.jpg)
Android 7.1.1 Nougat on a tablet

**Comment by ferraridamiano** [comment]
Thank you! I was able to reproduce the issue! This is a problem for android device below android 8.0. I will fix it soon

**Comment by ferraridamiano** [comment]
Just pushed this fix in v.3.0.1. It will land in the play store in the next few hours and in fdroid in the next few days

**Comment by Thewisem** [comment]
K thanks :)
