### ISSUE TITLE
[bug] Unable to reorder units for the first property

### ISSUE THREAD

**Issue by u2code** [ferraridamiano/ConverterNOW#106]
Hi @ferraridamiano 
I found a small bug when running Version 3.0.0 on Android (v 11). The version 3.0.1 is not available on F-Droid at the moment yet for me. 

**Settings** -> **Reorder units** -> when clicking on the first entry, nothing happens. 
Everything works fine for all other  in the list.

It has nothing to do with a special property itself. When I choose **Time** to the the first property, then I'm unable to edit the order of units within **Time**. If I choose **Volume** to be the first property, then I'm unable to edit the order of units within **Volume**.

Would be great if you could fix it.

Ciao!
@u2code

**Comment by ferraridamiano** [comment]
Thank you @u2code! Yeah, I'm able to reproduce the issue. I will fix it
