### ISSUE TITLE
[bug] Input issues on some instances

### ISSUE THREAD

**Issue by 1alessandro1** [ferraridamiano/ConverterNOW#116]
First of all, thank you for this great converter. The UI is very well made, and having conversions in real time makes everything feel very snappy.

The only bug I found so far with your app on Android 11, is the fact that sometimes, when typing into a box with some input (e.g. feet in the Length section) and then I press backspace multiple times to delete my input and try a new one, the app seems unresponsive towards any number I press. The only way to workaround this, is to switch to another unit of measurement or change the input textbox.

I've made a video with the issue I saw, I hope you'll find it useful

https://user-images.githubusercontent.com/46293832/140299994-7fb4fb72-c7c9-4980-bc48-db50e7ab7130.mp4

**Comment by ferraridamiano** [comment]
Hi @1alessandro1, thank you for reporting this. I confirm you that I'm able to reproduce it. I will try to fix it

**Comment by 1alessandro1** [comment]
Thank you. Is it possible to download the binaries from GitHub Actions?

https://github.com/ferraridamiano/ConverterNOW/actions/runs/1429848145

**Comment by ferraridamiano** [comment]
The action you linked is simply a test. You can download the binaries of the app when I publish a new release. You can find everything in the [release section](https://github.com/ferraridamiano/ConverterNOW/releases). They are the same binaries that you download on the playstore
