### ISSUE TITLE
Request to Add PKR Currency

### ISSUE THREAD

**Issue by aljawaid** [ferraridamiano/ConverterNOW#118]
**Description**
Kindly add Pakistani Rupee as a currency.  Also, please show where the currency rates are being updated from as I couldnt find that information in the app.  We generally use xe.com as our base rate so would be good to compare or even switch to the app if all our currencies are there.

**Units to be added**
| Unit name | Property | Reference to the conversion formula                |
| ----------| -------- | -------------------------------------------------- |
| Pakistani Rupee       | PKR | Rs.                                                 |

**Comment by ferraridamiano** [comment]
Hi @aljawaid. This app uses the api from ECB. Unfortunatly PKR is not included in the conversion. We use a free service since this is a free and open source app.

**Comment by aljawaid** [comment]
oh ok, good to know thanks
