### ISSUE TITLE
[feature] Fast way to copy the content of the textfield

### ISSUE THREAD

**Issue by aljawaid** [ferraridamiano/ConverterNOW#119]
**Description**
Hello, would be great if the windows desktpo version was able to minimise to the system tray and run in the background on Windows 10.  Also, would be great for notifications on the hour etc when the currency rates are updated.  Finally would be great if there was a copy to clipboard button next to each value to speed up copying values.

**Comment by ferraridamiano** [comment]
Hi @aljawaid and thank you for all this requests

1. This app includes a currency converter. But it's not a good idea to use this if you want to do money trading in realtime with the market. So the app updates the currency rates once every day (the date of the last update is clearly visible on the top of the currency page).
2. What is the purpose of keeping this app in the background? I'm just curious
3. Your last suggestion is great! I've already thinked to that, but a button next to each value is very ugly (see the image below). I have to think to a better way of doing it. If you have any idea I'm here to listen.

<img src="https://user-images.githubusercontent.com/34270884/143825328-f2dba35f-01dd-45df-9c2b-874d2020d18c.jpg" width="200"/>

**Comment by aljawaid** [comment]
hi @ferraridamiano 

1. I don't actually do money trading but I buy physical products from different countries primarily Pakistan. The currency rate, provided I know is coming from a legitimate source is good for a rference, which I saved manually on the invoices etc.  Ive started using volumes and lengths in the app so I just thought, if the currency that I need is there, I wont need to keep going to a website as some rates are passed over the phone amongst colleagues.
2.  In the background.... quick access, with a windows shortcut... im converting lengths and calculating product volumes etc most of my working day
3. how about copy to clipboard next to the unit label instead of under it? the app animation is great so maybe slide it in once there is a value in the field... cant remember if there is, but if there isnt then maybe add a clear field X inline too

**Comment by ferraridamiano** [comment]
1. Do you think a daily currency rate update is enough for your needs?
2. I think there isn't a big difference between keep it in the tray and minimizing it in the bottom bar. What am I missing?
3. You mean the unit of measurement box becomes also a "copy to clipboard" button? And yes there's already a "clear all" button

**Comment by aljawaid** [comment]
1. yeah
2. bottom bar gets in the way on laptops with full width taskbars
3. yes so next to the label unit, the clear field icon and the copy value icon... all inline in the field once there is a value

**Comment by ferraridamiano** [comment]
I will explore your last point in the future. I change the title of the issue for now
