### ISSUE TITLE
[Linux] Add Appimage support

### ISSUE THREAD

**Issue by docop** [ferraridamiano/ConverterNOW#125]
Hi  so your app is very great and quite usefull. I also wonder if it can be made fully portable ? As many ubuntu pc and so on direct machine control and so.. a simple : Appimage  ready to run, no internet required can be very usefull.

Thanks in advance

**Comment by ferraridamiano** [comment]
Hi @docop, currently you can install the app just with snap or compiling the code. Unfortunatly I'm not experienced in linux app packaging. But maybe in the future someone could contribute adding a appimage packaging to the ci/cd pipeline.

**Comment by docop** [comment]
Thanks again. Indeed i'm not good at programming either.. but for sure an executable appimage can run better than having to decompress the git folder.. and pc not having the package to build code and so.  as to run, on pc without inet
