### ISSUE TITLE
[web] Issue with MacOS

### ISSUE THREAD

**Issue by milotype** [ferraridamiano/ConverterNOW#171]
The link [converter-now.web.app](https://converter-now.web.app/) doesn't seem to work. It opens an empty page!

MacOS 10.11.6, Firefox, Safari

**Comment by ferraridamiano** [comment]
Hi @milotype, sorry for the delay. I have not a Mac, but I tested it on Firefox as well as on Chrome on Linux and it works. Could you try opening also https://gallery.flutter.dev . It is a website made with the same technology as Converter NOW. Let's see if it is a problem of this app or maybe related to browser/OS/framework.

**Comment by milotype** [comment]
@ferraridamiano yes, https://gallery.flutter.dev opens up a page with an animated icon.

**Comment by ferraridamiano** [comment]
Just an animated icon? Don't you see this?
![Screenshot_20220805_133152](https://user-images.githubusercontent.com/34270884/183068947-09f8f45f-41e6-4707-ae78-b7cb881cf2eb.png)

**Comment by milotype** [comment]
No. I see only this animated icon beating like a heart:
![icon](https://user-images.githubusercontent.com/43657314/183071101-8095bc5d-9ddb-459b-85db-8fdf0f882918.png)

**Comment by ferraridamiano** [comment]
That's the splashscreen, then it should open the web app. It is probably an issue with flutter and macos. Maybe you can try opening an issue [there](https://github.com/flutter/gallery). Since I can not reproduce the error I can not do it for you unfortunately. That repo is a showcase of flutter mantained by the flutter team. If they can fix the error in the framework, all the other apps that uses it (including converter now) will receive the fix. Thank you!

**Comment by milotype** [comment]
@ferraridamiano Just to inform you, the website works on my iPhone6, OS 12.5.5 !!

**Comment by ferraridamiano** [comment]
Good! But the issue still persists on MacOS. So, please report the issue on Flutter gallery

**Comment by milotype** [comment]
Flutter gallery doesn't work on my iPhone6, OS 12.5.5 either. But I've sent an issue at https://github.com/flutter/gallery/issues/748

**Comment by ferraridamiano** [comment]
Thank you!

**Comment by milotype** [comment]
@ferraridamiano Just checked - your page https://converter-now.web.app/ works with Safari 11.1.2 (11605.3.8.1) on my MacOS.
Only with Firefox 78.15.0esr (64-bit) it doesn't.

**Comment by milotype** [comment]
@ferraridamiano As I expected my Mac is simply too old ...
See the response on https://github.com/flutter/gallery/issues/748
I think you can close this issue as well.
