### ISSUE TITLE
[BUG]  Currencies Not Updated On Web

### ISSUE THREAD

**Issue by the7thNightmare** [ferraridamiano/ConverterNOW#191]
**Describe the bug**
In the web version, the currencies seems not updating, in F-Droid version it is already updated, but in the web version it is not (updated one year ago).

**To Reproduce**
1. Go to the web version of the app ([example](https://converter-now.web.app))
2. Click on Currencies
3. Look to the last update 

**Expected behavior**
A regular currencies update.

**Screenshots / gif**

**Device**
- Device type: Web
- OS version: [e.g. Android 11]
- Device type: [e.g. Google Pixel 6, Galaxy S21]

**Additional context**

**Comment by ferraridamiano** [comment]
Hi @the7thNightmare and thank you. But unfortunately, I can't do nothing about it. It's a [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) security limitation. I can not overcome since I do not control the echange rate service server.

**Comment by Kreuger** [comment]
Would this also effect the android app? Cause it no longer works for me.

**Comment by ferraridamiano** [comment]
@Kreuger nope, just web. Could you please open a new issue and describe the problem in details? Thank you!
