### ISSUE TITLE
[new-unit] Add chilean peso CLP

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [ferraridamiano/ConverterNOW#197]
**Description**
It would be good to have chilean pesos CLP in the converter. I guess the answer will be that it is not available in the ECB API you use. By the way, maybe we could check that ourselves instead of openning an issue? But I did not find what currencies are available with this API.

**Units to be added**
| Unit name | Property | Reference to the conversion formula                |
| ----------| -------- | -------------------------------------------------- |
| CLP       | Currency | /                                                  |

While I'm here, I'd like to thank you for your work, it's a really great app (even without CLP) :smile:

**Comment by ferraridamiano** [comment]
Hi @GuillaumeLeGoc and thank you for reporting this. You already know the answer unfortunately. You could check all the avialable currency [here](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html).
