### ISSUE TITLE
[BUG] Currencies don't update with the latest version

### ISSUE THREAD

**Issue by Kreuger** [ferraridamiano/ConverterNOW#211]
Hey since I updated the app to version 4 on Android, the page just shows up blank.

![Screenshot_20230213-184803](https://user-images.githubusercontent.com/42020/218600392-16a050bc-cbef-4b67-bcdc-4ae9aef5bcfe.jpg)

**Comment by ferraridamiano** [comment]
Hello @Kreuger, I am aware of this problem, unfortunately the fix is not super-easy and I don't have that much time. But **you can fix it by clearing all the app data**. I pin this issue because I think that also other people will notice this bug.

**Comment by Kreuger** [comment]
Great, thanks. Its worth noting that clearing the cache isnt enough, you have to clear the storage.

**Comment by ferraridamiano** [comment]
I just released v4.0.1 that fix this bug
