### ISSUE TITLE
[new-unit] Voltage divider

### ISSUE THREAD

**Issue by virtadpt** [ferraridamiano/ConverterNOW#213]
**Description**
A voltage divider calculator would be very helpful.  Mostly because half the pages on the Net get it wrong (they swap r1 and r2, which gives bad values).  Having a one-stop known-good calculator handy at all times would be extremely helpful.

**Units to be added**
| Unit name | Property | Reference to the conversion formula                |
| ----------| -------- | -------------------------------------------------- |
| Input voltage  | Vin   | [link](https://ohmslawcalculator.com/voltage-divider-calculator)     |
| r1     | Resistance of r1 in ohms     |  |
| r2     | Resistance of r2 in ohms |  |
| Output voltage | Vout |  |

**Comment by ferraridamiano** [comment]
Hello @virtadpt
At the moment this app is only focused on conversion (and not tools). It would be nice to have tools, but unfortunately I don't have enough time to implement them. Feel free to fork the repo or submit a PR

**Comment by virtadpt** [comment]
Oh, okay.
