### ISSUE TITLE
English misspelling

### ISSUE THREAD

**Issue by syu-pf-ssy** [ferraridamiano/ConverterNOW#222]
I found some English misspelling when I translated from English to Chinese.
I found this mistake on [ConverterNOW/fastlane/metadata/android/en-US/full_description.txt](https://github.com/ferraridamiano/ConverterNOW/tree/master/fastlane/metadata/android/en-US/full_description.txt)

mesurement to measurement on line 12
atomsfere to atmosphere on line 24
horse power to  horsepower on line 26
metre to meter on line 29 (maybe)

I didn't fix those translations because my English is not very good(actually a chrome function found those mistakes)
So I'm not sure if the point I pointed out is really wrong.
If anyone has time, please fix this.
Thank you!

**Comment by ferraridamiano** [comment]
Thank you for pointing this out! I will fix them!
