### ISSUE TITLE
[BUG]  Numbers that starts with . should be allowed

### ISSUE THREAD

**Issue by atom-smasher** [ferraridamiano/ConverterNOW#225]
**Describe the bug**
Entering a value the starts with a decimal/dot causes an error: "Error, invalid characters".

**To Reproduce**
1. Go to "Length"
2. Click on "Meters"
3. Enter ".5"
5. See error

**Expected behavior**
A leading zero should be implied when a leading decimal/dot is entered. eg ".5" should be read as "0.5". This seems to apply to all units.

**Screenshots / gif**
N/A

**Device**
- Device type: Android
- OS version: Android 10
- Device type: Moto G Power

**Additional context**
N/A

**Comment by ferraridamiano** [comment]
Good point. This is any easy fix, I will mark it as "good first contribution"

**Comment by HarshMakwana27** [comment]
can i work on this ?

**Comment by ferraridamiano** [comment]
> can i work on this ?
> 

Of course! Thank you!

**Comment by HarshMakwana27** [comment]
Solved and sent a pull request
