### ISSUE TITLE
Shoe sizes are off

### ISSUE THREAD

**Issue by dizietsma** [ferraridamiano/ConverterNOW#23]
Here in the UK a size 9 is about EU 43, according to your converter, which looks really nice, an EU size 43 is UK 7.08 for men.  I wear uk size 9 shoes and they have EU43 marked on them.  Every other conversion list I can find online agrees with my shoes.

diziet

**Comment by ferraridamiano** [comment]
Thanks @dizietsma, you are right, there was an error in the conversion. I'm fixing it. Although I noticed that there isn't a single equation for shoe size conversion, but usaually there are many tables with different values. I use the conversion formula that I found on wikipedia, but according to the table you are watching there could be a small error.

**Comment by dizietsma** [comment]
That was fast, nice:)
