### ISSUE TITLE
kWh to watts?

### ISSUE THREAD

**Issue by virtadpt** [ferraridamiano/ConverterNOW#231]
**Description**
Being able to convert kWh (kilowatt hours) to watts would be handy.  When trying to figure out how much power one is drawing at home (something of concern to everyone who has a homelab, especially in an older house).  Especially when the most commonly available power monitoring devices out there can only provide measurements in kWh (and the more useful ones must be wired directly into the house's power lines (as I found out the hard way...))

Looking at my installation of Converter NOW, in the Energy category kWh can be converted into joules, calories, electron volts, and foot-pounds.  Additionally, in the Power category, watts can be converted into milliwatts, kilowatts, megawatts, gigawatts, European horsepower, and imperial horsepower.  But there is no conversion of kilowatt-hours into watts.

kWh to watts: https://www.energuide.be/en/questions-answers/how-can-i-calculate-the-consumption-of-an-electrical-appliance/94/

**Comment by ferraridamiano** [comment]
Hello @virtadpt!
kWh is a an energy unit, while W is a power unit. You can't convert between the two. It would be like converting 1 celsius to meters, it does not make any sense.
Maybe what you are looking for is a tool where given the usage time and the power draw of a device computes the total amount of energy. But this is not a conversion. Converter NOW at the moment is focused only on conversions

**Comment by TryTryAgain** [comment]
I was looking for this as well, @ferraridamiano so this is not true? https://www.inchcalculator.com/watts-to-kwh-calculator/ 

<img width="207" height="92" alt="Image" src="https://github.com/user-attachments/assets/c67e4ed9-ea65-459d-831b-22bd564ff68f" />

**Comment by ferraridamiano** [comment]
Hello @TryTryAgain 

That formula is correct, but as you can see combining time and power gives you energy, it's not a conversation but a formula that combines different properties together. While a conversion converts a unit to another unit of the same property.

It's like saying that 1 km/h is kilometers divided by hours. This is not a conversion but a combination of different properties. While saying that 3.6 km/h is 1 m/s is a conversion because it involves the same property. Hope it's clear

**Comment by TryTryAgain** [comment]
Understood, makes sense. So no interest in supporting formulas like this then?

**Comment by ferraridamiano** [comment]
Unfortunately I don't have enough time to invest in this project for such a big addition
