### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by HarshMakwana27** [ferraridamiano/ConverterNOW#236]
**Describe the bug**
The Icon for navigation drawer is overlapping

**To Reproduce**
1. Scroll down 
2. See error

**Expected behavior**
It should be moved or disappeared

**Screenshots / gif**

<img src="https://github.com/ferraridamiano/ConverterNOW/assets/133812075/34e21ae9-4762-475e-ab1c-c59f91dd420a" height="600">

<img src="https://github.com/ferraridamiano/ConverterNOW/assets/133812075/6fffcd27-374d-4dbb-ae74-c25268cb6148" alt="Girl in a jacket" height="600">

**Device**
Android (Realme GT neo2)

**Comment by ferraridamiano** [comment]
This is a flutter bug that was introduced with the latest stable. If you compile the app with the previous stable or beta version this bug will not appear. Since this will be fixed with the next flutter stable version I close this issue
