### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [ferraridamiano/ConverterNOW#237]
So the current build failed
```
ERROR: Could not build app com.ferrarid.converterpro: Some glob paths did not match any files/dirs: android/app/proguard-rules.pro
```
...an easy fix, and I also update Flutter to 3.13.0, right https://github.com/ferraridamiano/ConverterNOW/commit/1ab0a1a07dcfc118a2baad9c1e8572e1bdaff9f5  ?

but that fails:
```
...
+ yaml_edit 2.1.1
Building package executables...
Built melos:melos.
Installed executable melos.
Activated melos 3.1.1.
+ dart pub global activate vector_graphics_compiler
Resolving dependencies...
+ args 2.4.2
+ collection 1.18.0
+ meta 1.9.1
+ path_parsing 1.0.1
+ petitparser 6.0.1
+ vector_graphics_codec 1.1.7
+ vector_graphics_compiler 1.1.7
+ vector_math 2.1.4
+ xml 6.4.2
Building package executables...
Built vector_graphics_compiler:vector_graphics_compiler.
Installed executable vector_graphics_compiler.
Activated vector_graphics_compiler 1.1.7.
+ melos bootstrap
Resolving dependencies...
Because every version of flutter from sdk depends on sky_engine from sdk which doesn't exist (could not find package sky_engine in the Flutter SDK), flutter from sdk is forbidden.
So, because converterpro depends on flutter from sdk, version solving failed.
```

The odd thing is that looking at the [Github CI pipeline](https://github.com/ferraridamiano/ConverterNOW/actions/runs/5889315495/job/15972239960) for the Tag commit, versions are different 
```
 Resolving dependencies...
 args 2.4.2
 collection 1.18.0
 meta 1.9.1
 path_parsing 1.0.1
 petitparser 5.4.0
 vector_graphics_codec 1.1.7
 vector_graphics_compiler 1.1.7
 vector_math 2.1.4
 xml 6.3.0
```
...at least for petitparser and xml. Why? Isn't the .lock file ummm locking them?

Thoughts?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/d4fb3f823dfeb893f30606cccda3da40a457d17e

**Comment by licaon-kter** [comment]
> I'm taking a look to the CI of your commit, but to me the build seems successfull , isn't it?

That's what I said too, but why are the deps versions **different** in your CI?

**Comment by ferraridamiano** [comment]
The first block of code refers to the dependencies of the dev tools (i.e.. `melos` and `vector_graphics_compiler`), they are compiled with the versions of the dependencies defined in their own lock file. While the latest block of code refers to the dependencies of this app.

If theissue is resolved, we can close it

**Comment by licaon-kter** [comment]
I didn't retry yet, so nothing is fixed :shrug:

**Comment by licaon-kter** [comment]
@ferraridamiano here's the full log: 
[com.ferrarid.converterpro_40.log.gz](https://github.com/ferraridamiano/ConverterNOW/files/12426445/com.ferrarid.converterpro_40.log.gz)

**Comment by ferraridamiano** [comment]
I managed to fix the build error. I submitted a [MR](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13618)
