### ISSUE TITLE
[BUG] Currency values do not update with current rates

### ISSUE THREAD

**Issue by gitucer** [ferraridamiano/ConverterNOW#239]
"shared_preferences.json" doesn't update with current currency rates on Windows

**To Reproduce**
1. Open Currencies section
2. Check "Last update:" text as well as the shared_preferences.json in the Roaming AppData folder
3. Last update shows 1/13/2023
4. Does not update with current values

**Comment by ferraridamiano** [comment]
I'm not sure why this is happening, windows is the only OS that shows this error. It looks like there is a problem with the cerficate of the API service. A poosible fix would be to accept all the certificates, but I don't want to do it for obvious reasons
