### ISSUE TITLE
[Feature Request] Multi-platform Container Image

### ISSUE THREAD

**Issue by matt-laird** [ferraridamiano/ConverterNOW#241]
I think it would be great to be able to self-host the tool by building and publishing a container image for the web version of the app.

**Comment by ferraridamiano** [comment]
Oh, this is pretty easy to do. I marked it as a good first contribution!

**Comment by benni347** [comment]
Hey @ferraridamiano could I work on it?

**Comment by ferraridamiano** [comment]
Of course @benni347
