### ISSUE TITLE
"Numeral systems" conversion can give incorrect answers for hexadecimal input

### ISSUE THREAD

**Issue by jtn20** [ferraridamiano/ConverterNOW#28]
If I go to the "Numeral systems" screen, and type "8e" or "8E" into the "Hexadecimal" box, the other boxes show incorrect answers:

- Decimal: 852 (should be 142)
- Binary: 101100000 (should be 10001110)
- Octal: 540 (should be 216)

Visible in both Android app (2.4.1, F-droid) and on [website](https://ferraridamiano.github.io/ConverterNOW/) at time of writing.

**Comment by ferraridamiano** [comment]
You are rigth, I will fix this ASAP

**Comment by ferraridamiano** [comment]
Thanks @jtn20, I fixed it. It was a big bug! It will be available in the next release
