### ISSUE TITLE
[feature] Back Button pressed on Settings should open Sidebar

### ISSUE THREAD

**Issue by skj-skj** [ferraridamiano/ConverterNOW#282]
# Feature
When Back Button pressed or Swipe action for back is done on Settings it should show sidebar again.

# Why?
on Android when I change settings I expect to use the conversion app and hoping back button will show me the default conversion screen or sidebar. but instead I get exited from the app.

it feels natural to press back button or swipe action for back when you are on setting page. for user pov the setting page is like stacked on the app and have to remove in order to go to previous page.

I have created this issue for setting but it can be expanded on the whole application for all conversion sections on sidebar.

**Comment by ferraridamiano** [comment]
I am aware of this issue. But it needs a fix from go_router / flutter side

Blocked by: https://github.com/flutter/flutter/issues/140869

Upvote that issue

**Comment by ferraridamiano** [comment]
This issue is now fixed with the latest commit. Unfortunately I used a workaround to make it work, the issue mentioned above still exists
