### ISSUE TITLE
[Bug] Small font size for the "Theme color" string

### ISSUE THREAD

**Issue by Vsnmrn** [ferraridamiano/ConverterNOW#290]
**Describe the bug**
Hello!
This is a very very little bug but I noticed the string added in order to customise the app color is smaller than the other strings you can read in the settings: 

**Screenshots / gif**
![Screenshot_20240605_183255](https://github.com/ferraridamiano/ConverterNOW/assets/146990829/d573d095-eb99-4c2c-8689-5fdcf4075788)

**Device**
- Device type: Android and Web
- OS version: Android 14
- Device type: Samsung A54

**Additional context**
I was using the default system font.

**Comment by ferraridamiano** [comment]
This is fine. Take a look at a typical material 3 page (this for example is from a pixel device in the phone settings):

![Screenshot.png](https://github.com/ferraridamiano/ConverterNOW/assets/34270884/262030ea-d78d-4fa8-9698-2adfb78829fc)
