### ISSUE TITLE
No icon after installing in Windows 11

### ISSUE THREAD

**Issue by janneroyibo** [ferraridamiano/ConverterNOW#292]
Just installed the app in Windows 11 via Microsoft store and works correctly however there is a blank icon for the app in start menu.

**Comment by ferraridamiano** [comment]
Could you please try reinstalling the app?

**Comment by janneroyibo** [comment]
I uninstalled and then reinstalled via Microsoft Store and had same problem.

I then tried to install with the .msix file downloaded from github but can’t install that as i.m getting the message below :-
***@***.***

***@***.***

**Comment by ferraridamiano** [comment]
I can not reproduce the problem

**Comment by ferraridamiano** [comment]
I am now able to verify the problem. I will work on a fix
