### ISSUE TITLE
Add keyboard shortcuts

### ISSUE THREAD

**Issue by joenepraat** [ferraridamiano/ConverterNOW#298]
When I try to search in ConverterNOW I tried ctrl+f first. Unfortunately it didn't work and it seemed ConverterNOW doesn't have shortcuts at all. So maybe binding at least ctrl+f and / to search would be great.

Thanks.

**Device**
- Device type: Linux PC
- OS version: Ubuntu 24.04
- DE: GNOME 46
- Version: 4.2.2 (flatpak)

**Comment by ferraridamiano** [comment]
Done! This will be available in the next release. The shortcut will be ctrl+k for opening search
