### ISSUE TITLE
[BUG] [Android] [Regression] Themed Launcher app icon no longer appears

### ISSUE THREAD

**Issue by sebastien46** [ferraridamiano/ConverterNOW#313]
**Describe the bug**

Since commit 62d1b58, the `android/app/src/main/res/mipmap-anydpi-v26` folder was removed & the ability to display a themed / monochrome Launcher app icon along with it.

**To Reproduce**
1. Go to the Android Launcher with Themed Icons enabled
2. Add Converter Now to the Launcher if not already present
3. Observe app icon
4. It isn't themed like it should

**Expected behavior**
The Launcher app icon should be themed like it was before the aforementioned commit.

**Screenshots / gif**
![ResizedImage_2024-12-05_12-46-06_3401](https://github.com/user-attachments/assets/3d399334-98b4-4f6d-91b6-e9ac8f3a9f55)

**Device**
- Device type: Android
- OS version: 15
- Device type: Google Pixel 7

**Additional context**

**Comment by ferraridamiano** [comment]
I can confirm that the issue exists and I will fix it for sure before the next release
