### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Sthaagg** [ferraridamiano/ConverterNOW#315]
**Describe the bug**
Using the command `docker run -d -p 80:80 ghcr.io/ferraridamiano/ConverterNOW:latest` leads to the following error:
`docker: invalid reference format: repository name (ferraridamiano/ConverterNOW) must be lowercase`
If I use the command `docker run -d -p 80:80 ghcr.io/ferraridamiano/converternow:latest` instead, it leads to the followinf error: 
` ✘ ferraridamiano Error Head "https://ghcr.io/v2/ferraridamiano/converternow/manifests/latest": denied
Error response from daemon: Head "https://ghcr.io/v2/ferraridamiano/converternow/manifests/latest": denied
`
**To Reproduce**
1. Open a terminal
2. run the command `docker run -d -p 80:80 ghcr.io/ferraridamiano/ConverterNOW:latest` (From the readme) or ` docker run -d -p 80:80 ghcr.io/ferraridamiano/converternow:latest` 
3. See error

**Expected behavior**
A successful start.

**Device**
- Device type: Linux
- OS version: Ubuntu Server 24.04 LTS
- Docker version: 27.4

**Comment by ferraridamiano** [comment]
Yes, you are right!

This is because we just introduced docker for converter now, but you will be able to run it when I will release the next version (it will happen very soon)

I'm gonna close this, please be patient, thank you!

**Comment by Sthaagg** [comment]
I don't notice anything in the last changelog about this ?
Is it still in progress ?

**Comment by ferraridamiano** [comment]
I had issue with the release of the latest version. I am working on it right now

**Comment by ferraridamiano** [comment]
Done!

try it by running: `docker run -d -p 80:80 ghcr.io/ferraridamiano/converternow:latest`

**Comment by Sthaagg** [comment]
Works properly, this the compose for your file, just in case:
`services:
  convertnow:
    image: 'ghcr.io/ferraridamiano/converternow:latest'
    container_name: convertnow
    security_opt:
      - no-new-privileges:true
    restart: on-failure:5
    ports:
      - '80:80'`
