### ISSUE TITLE
(Improvement) True Black AMOLED Theme 

### ISSUE THREAD

**Issue by fux0r2009** [ferraridamiano/ConverterNOW#33]
Hi @ferraridamiano,

Please consider adding a true black theme to the app as the current theme is not bad but a true black theme would be better!

Thanks

**Comment by ferraridamiano** [comment]
Hi @fux0r2009 and thank you for your contribution! I will surely add this feature. Now I'm doing a complete app rewrite in my freetime (and it will take a while), but this will be the next thing!

**Comment by fux0r2009** [comment]
@ferraridamiano Very glade to hear it and looking forward to it!!

**Comment by ferraridamiano** [comment]
AMOLED dark theme implemented! Hope you will like it 😉

<img src="https://user-images.githubusercontent.com/34270884/107887689-34baa200-6f08-11eb-9634-ad027b1aa891.png" width="300" />

**Comment by fux0r2009** [comment]
@ferraridamiano WONDERFUL ! I love it :) Finally a real Theme for this awesome app !
