### ISSUE TITLE
Name problem

### ISSUE THREAD

**Issue by Torok42** [ferraridamiano/ConverterNOW#39]
Hi @ferraridamiano,

First thank you for this application :-)

In the search, there is a problem if the name is on multiple lines

![Sans titre](https://user-images.githubusercontent.com/58152695/106329253-2190ac80-624f-11eb-98a9-3accdbff43ca.jpg)

**Comment by ferraridamiano** [comment]
Hi @Torok42 and thank you for reporting this issue. I wil fix this in future release
Best regards!

**Comment by ferraridamiano** [comment]
Hi @Torok42 could you tell me what phone are you using?

**Comment by Torok42** [comment]
Hi @ferraridamiano, I have a Samsung A51 with Android 10

**Comment by ferraridamiano** [comment]
Thank you @Torok42! I was finally able to reproduce this issue and i fixed it!
It's not always easy to reproduce them because of various screen size and display density

**Comment by Torok42** [comment]
@ferraridamiano well done!
