### ISSUE TITLE
New icons!

### ISSUE THREAD

**Issue by ferraridamiano** [ferraridamiano/ConverterNOW#44]
At the moment every icon has a different style and not every icon looks nice. I am not good with graphics, so if you are you can contribute to this project! You can post here below your suggestions. Then I will tell you how you can submit a PR.

**Comment by fux0r2009** [comment]
hi @ferraridamiano I don't want to sound stupid but why not use the google material design icons https://material.io/resources/icons/?style=baseline as they contain a lot of the already implemented icons ??

**Comment by ferraridamiano** [comment]
Thank you for your suggestions! I already use flaticon/freepik icons but each has a different style.
Material icons are awesome but there aren't all the icons I need. There is not an icon for pressure, mass, fuel, shoe size, torque, etc.
But the icon for time that I use is the material icon.

I would like to have a unique style for every icon

**Comment by iamdamar** [comment]
@ferraridamiano Hi. I think the icons should be in outline style when normal and then turned to glyph style when clicked. I would like to contribute if you're okay with my suggestion.

**Comment by ferraridamiano** [comment]
Hi @iamdamar, thank you! I would be very happy! Can you post just a couple of examples so we will decide together?

**Comment by iamdamar** [comment]
Like this. The left one is when it's in normal state, and the right one is when it's in clicked state.

![20210217_174148](https://user-images.githubusercontent.com/79195688/108193148-b9473380-7147-11eb-8f1f-95c00cca3170.jpg)

**Comment by ferraridamiano** [comment]
Yes, I understood the difference. But the icons should come with permissive license (such as creative commons). Or can you design it?
