### ISSUE TITLE
High CPU usage on Linux

### ISSUE THREAD

**Issue by pizzadude** [ferraridamiano/ConverterNOW#68]
The Linux version takes up 60-70% of my CPU usage on Fedora 33 KDE. I installed it via the snap store.

Any idea why? Is it a flutter bug?

Specs:
```
Kernel: Linux 5.10.20-200.fc33.x86_64 x86_64
Distro: Fedora release 33 (Thirty Three)
CPU:    Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
        4 cores/threads
        3500.00 MHz
RAM:    7.61 GiB
GPU:    Mesa Intel(R) HD Graphics 620 (KBL GT2)
        OpenGL 4.6 (Compatibility Profile) Mesa 20.3.4
        GLSL 4.60
```

**Comment by ferraridamiano** [comment]
Hi @pizzadude and thank you for reporting this issue! It could be a flutter bug, on my notebook (quite similar to yours) it takes 15% of CPU usage. Flutter for Linux is still in beta and I compiled 2.5.0-rc0 with an alpha version. In the next days I will recompile the last version of this app (2.5.0, solves some bug compared to 2.5.0-rc0) with the latest beta version of flutter.

In the meanwhile: could you try to install [flutter-gallery](https://snapcraft.io/flutter-gallery) and tell me if the situation is the same?
Thank you!

**Comment by pizzadude** [comment]
Hi, yes, flutter-gallery has the same issue. Both your app and flutter-gallery also cause high CPU usage in Xorg.

**Comment by pizzadude** [comment]
Wait, what are you using to calculate CPU usage? If I use ksysguard, it shows 15% CPU but If I use "top" (command line utility) it shows 60-70% CPU so that means it's using 60-70% of one core but the GUI system monitor apps are calculating it based on all cores combined.

**Comment by ferraridamiano** [comment]
You are right! I will report it to the flutter team
Thank you!

**Comment by ferraridamiano** [comment]
I reported the problem to the flutter team [here](https://github.com/flutter/flutter/issues/77710) and they confirm that the issue exists.

**Comment by ferraridamiano** [comment]
They fixed the issue. I'm waiting for the fix being rolled to master/dev channel.
