### ISSUE TITLE
hitting full screen on ubuntu causes syetm lock up 

### ISSUE THREAD

**Issue by CadMunkey** [ferraridamiano/ConverterNOW#91]
virgin install from Ubuntu Software..... Click to open app.....Opens.... Hit Maximise... Full system lock up... Reboot.  launch app... opens and instantly closes.

**Comment by ferraridamiano** [comment]
Hi @CadMunkey, I tried to do what you suggested but I'm not able to reproduce this issue. I'm using kubuntu 20.10.
I ask you to try to do 2 things:
1. Could you please try to install [this app](https://snapcraft.io/flutter-gallery) and tell me if it ha the same problem (it is built with the same framework)?
2. Could you try to launch the app from the terminal? Just type `converternow`, hit maximize and than paste here the output of the terminal?

Thank you

**Comment by CadMunkey** [comment]
Hi, typically... Now I have highlighted was happened to you I also can't reproduce the crash.... Maybe it was something happening with my system rather than the app. It seems to be working fine now.

I'm quite impressed with what you have created. 

PS.. apologies if my initial post was a bit blunt.. It wasn't supposed to be
