### ISSUE TITLE
Fix wrong Russian translation

### ISSUE THREAD

**Issue by ashed** [ferraridamiano/ConverterNOW#95]
I fixed wrong Russian translation.
Add it to upstream please.
[full_description-ru.zip](https://github.com/ferraridamiano/ConverterNOW/files/6951084/full_description-ru.zip)

**Comment by ferraridamiano** [comment]
Hi, thank you for your contribution. Could you please open a pull request and submit the translation?
If you need help, please let me know

**Comment by ashed** [comment]
OK. What I can do for this? Get whole repo of ConverterNOW and then pull request with fixed translation, isn't it?

**Comment by ferraridamiano** [comment]
Yeah, fork the repo, then clone your fork, apply your changes and commit&push them. Finally open a pull request. That's it! 😉

**Comment by ferraridamiano** [comment]
I'm closing this for now. Feel free to reopen if you need further help!
Thank you!
