### ISSUE TITLE
Add currency TWD

### ISSUE THREAD

**Issue by cocomango1** [ferraridamiano/ConverterNOW#99]
hello,
great app, I love it so far,  but I miss the currency TWD = NT$.
I would be unique for your app, because no other app does.
Hope there is a possibiltiy to add, thanks.
https://cuex.com/en/eur-twd

**Comment by ferraridamiano** [comment]
Hi @cocomango1, thanks for your suggestion. I add conversions that the people need. There are tons of units and exchange rates. But if this could be helpful to you I will add it in the next release
